- name: cron environment
  cron:
    name: 'env {{ item }}'
    job: ''
    minute: '{{ item }}'
    hour: ''
    day: ''
    weekday: ''
    month: ''
  loop:
  - SHELL=/bin/bash
  - HOME={{ ansible_env.HOME }}


- name: clean up projects
  cron:
    minute: '21'
    name: remove tox dirs older than 4 weeks
    job: find ~/Documents/Projects -type d -iname '.tox' -ctime +4w -delete
