- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
  - innotop
  - ipython
  - ipython/profile_default
  - ipython/profile_default/startup
  - config
  - config/karabiner
  - config/yamllint

- name: dotfiles files
  file:
    src: '{{ ansible_env.PWD }}/roles/phoebe_mac/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - config/karabiner/karabiner.json
  - config/yamllint/config
  - gitconfig
  - gitignore_global
  - ssh/config
  - ansible.cfg
  - ipython/profile_default/startup/00-imports.py

- name: innotop.conf
  copy:
    src: dotfiles/innotop/innotop.conf
    dest: ~/.innotop/innotop.conf
    force: false  # Only if it doesn't exist

- name: pypirc
  copy:
    src: dotfiles/pypirc
    dest: ~/.pypirc
    force: false


